--1st
CREATE VIEW list_of_all_books_in_stock
AS
SELECT TITLE, AUTHOR
FROM N5_BOOK
WHERE COPIES_IN_STOCK > 0;

SELECT * from FN71871.list_of_all_books_in_stock;

--2nd
CREATE VIEW purchase
AS
SELECT CARDHOLDER_FIRST_NAME || ' ' || CARDHOLDER_LAST_NAME AS NAME, TOTAL_PRICE
FROM N9_PAYMENT, N10_ORDER
WHERE PAYMENT_ID = ORDER_PAYMENT_ID;

SELECT * FROM purchase;

--3rd
CREATE VIEW company_payments
AS
SELECT EMP_FIRST_NAME || ' ' || EMP_LAST_NAME AS NAME, WORK_DEPT, EMP_JOB, SALARY, BONUS
FROM FN71871.N2_EMPLOYEE
WHERE ED_LEVEL = 12;

SELECT * FROM company_payments;

 