CREATE TABLE N1_DEPARTMENT
(
    DEPT_ID CHAR(4) NOT NULL
        CONSTRAINT PK_DEPT PRIMARY KEY,
    DEPT_NAME VARCHAR(36) NOT NULL,
    MGR_ID CHAR(6) NOT NULL
);

CREATE TABLE N2_EMPLOYEE
(
    EMP_ID CHAR(6) NOT NULL
        CONSTRAINT PK_EMPLOYEE PRIMARY KEY,
    EMP_FIRST_NAME VARCHAR(36) NOT NULL,
    EMP_LAST_NAME VARCHAR(36) NOT NULL,
    WORK_DEPT CHAR(4) NOT NULL
        CONSTRAINT FK_EMPLOYEE_DEPARTMENT REFERENCES N1_DEPARTMENT (DEPT_ID),
    EMP_JOB VARCHAR(20) NOT NULL,
    EMP_PHONE_NO CHAR(10) NOT NULL,
    HIRE_DATE DATE NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    ED_LEVEL INTEGER NOT NULL
        CONSTRAINT CHK_ED_LEVEL CHECK ( ED_LEVEL >= 12 ),
    UNIVERSITY VARCHAR(36),
    SEX CHAR(1) NOT NULL
        CONSTRAINT CHK_SEX CHECK ( SEX IN ('M', 'F') ),
    SALARY DECIMAL(8, 2) NOT NULL,
    BONUS DECIMAL(6, 2) NOT NULL
);

--ÏÐÎÌÅÍßÌ ÑÕÅÌÀÒÀ ÄÅÏÀÐÒÌÅÍÒ ÇÀ ÄÀ ÃÈ ÑÂÚÐÆÀ ×ÐÅÇ ÔÊ
ALTER TABLE N1_DEPARTMENT
ADD CONSTRAINT FK_MANAGER_EMPLOYEE
FOREIGN KEY(MGR_ID)
REFERENCES N2_EMPLOYEE(EMP_ID);

CREATE TABLE N3_WAREHOUSE
(
    WAREHOUSE_ID CHAR(5) NOT NULL
        CONSTRAINT PK_WAREHOUSE PRIMARY KEY,
    EMP_CONTACTED_BY CHAR(6) NOT NULL
        CONSTRAINT FK_WAREHOUSE_EMP REFERENCES N2_EMPLOYEE(EMP_ID),
    CONTACT_FIRST_NAME VARCHAR(36) NOT NULL,
    CONTACT_LAST_NAME VARCHAR(36) NOT NULL,
    WH_PHONE_NO CHAR(10) NOT NULL,
    WH_E_MAIL VARCHAR(50) NOT NULL,
    WH_ADDRESS VARCHAR(64) NOT NULL,
    WH_CITY VARCHAR(20) NOT NULL,
    WH_COUNTRY VARCHAR(20) NOT NULL,
    WH_ZIP CHAR(5) NOT NULL
);

CREATE TABLE N4_CATEGORY
(
    CATEGORY_ID CHAR(2) NOT NULL
        CONSTRAINT PK_CATEGORY PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL,
    NUM_OF_COPIES INTEGER
        CONSTRAINT CHK_CATEGORY_NUM_OF_COPIES CHECK (NUM_OF_COPIES >= 0)
);

CREATE TABLE N5_BOOK
(
    ISBN CHAR(13) NOT NULL
        CONSTRAINT PK_BOOK PRIMARY KEY,
    TITLE VARCHAR(64) NOT NULL,
    AUTHOR VARCHAR(64) NOT NULL,
    PUBLISHER VARCHAR(64) NOT NULL,
    GENRE_ID CHAR(2) NOT NULL
        CONSTRAINT FK_BOOK_CATEGORY REFERENCES N4_CATEGORY(CATEGORY_ID),
    LANGUAGE VARCHAR(20) NOT NULL,
    NUM_OF_PAGES INTEGER NOT NULL
        CONSTRAINT CHK_BOOK_PAGES CHECK ( NUM_OF_PAGES > 25 ),
    PUBLICATION_DATE DATE NOT NULL,
    COPIES_IN_STOCK INTEGER NOT NULL,
    IS_TEXTBOOK CHAR(1)
        CONSTRAINT CHK_BOOK_IS CHECK ( IS_TEXTBOOK IN ('Y','N') ),
    PRICE DECIMAL(5,2) NOT NULL
        CONSTRAINT CHK_BOOK_PRICE CHECK ( PRICE > 0 ),
    WAREHOUSE_FROM_ID CHAR(5) NOT NULL
        CONSTRAINT FK_BOOK_WAREHOUSE REFERENCES N3_WAREHOUSE(WAREHOUSE_ID),
    EMP_EDITED_BY CHAR(6) NOT NULL
        CONSTRAINT FK_BOOK_EMPLOYEE REFERENCES N2_EMPLOYEE(EMP_ID)
);

CREATE TABLE N6_USER
(
    USER_ID CHAR(7) NOT NULL
        CONSTRAINT PK_USER PRIMARY KEY,
    USER_FIRST_NAME VARCHAR(36) NOT NULL,
    USER_LAST_NAME VARCHAR(36) NOT NULL,
    USER_BIRTH_DATE DATE NOT NULL,
    USER_PHONE_NO CHAR(10) NOT NULL,
    USER_E_MAIL VARCHAR(50) NOT NULL,
    USER_ADDRESS VARCHAR(64) NOT NULL,
    USER_CITY VARCHAR(20) NOT NULL,
    USER_COUNTRY VARCHAR(20) NOT NULL,
    USER_ZIP CHAR(5) NOT NULL,
    DATE_JOINED DATE NOT NULL
);

CREATE TABLE N7_SHOPPING_CART
(
    SHOPPING_CART_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)
        CONSTRAINT PK_SHOPPING_CART PRIMARY KEY,
    CUSTOMER_ID CHAR(7) NOT NULL
        CONSTRAINT FK_SHPCRT_USER REFERENCES N6_USER(USER_ID),
    BOOK_TITLE VARCHAR(64) NOT NULL,
    BOOK_ISBN CHAR(13) NOT NULL
        CONSTRAINT FK_SHOPPINGCRT_BOOK REFERENCES N5_BOOK(ISBN),
    PRICE DECIMAL(5,2) NOT NULL
        CONSTRAINT CHK_BOOK_PRICE CHECK ( PRICE > 0 ),
    QUANTITY INTEGER
        CONSTRAINT CHK_QUANTITY CHECK ( QUANTITY > 0 )
);

CREATE TABLE N8_VOUCHER
(
    VOUCHER_ID CHAR(8) NOT NULL
        CONSTRAINT PK_VOUCHER PRIMARY KEY,
    DISCOUNT_PER INTEGER
);

CREATE TABLE N9_PAYMENT
(
    PAYMENT_ID CHAR(7) NOT NULL
        CONSTRAINT PK_PAYMENT PRIMARY KEY,
    SHOPPING_CART_ID INT NOT NULL
        CONSTRAINT FK_PAYMENT_SHOPPINGCRT REFERENCES N7_SHOPPING_CART(SHOPPING_CART_ID),
    CARDHOLDER_FIRST_NAME VARCHAR(36) NOT NULL,
    CARDHOLDER_LAST_NAME VARCHAR(36) NOT NULL,
    CARD_NO CHAR(16) NOT NULL,
    CARD_TYPE VARCHAR(25) NOT NULL,
    CARD_EXP_DATE DATE NOT NULL,
    CARD_SEC_CODE CHAR(3) NOT NULL,
    USED_VOUCHER_ID CHAR(8) NOT NULL
        CONSTRAINT FK_PAYMENT_VOUCHER REFERENCES N8_VOUCHER(VOUCHER_ID)
);

CREATE TABLE N10_ORDER
(
    ORDER_ID CHAR(8) NOT NULL
        CONSTRAINT PK_ORDER PRIMARY KEY,
    ORDER_PAYMENT_ID CHAR(7) NOT NULL
        CONSTRAINT FK_ORDER_PAYMENT REFERENCES N9_PAYMENT(PAYMENT_ID),
    STATE_OF_ORDER VARCHAR(20) NOT NULL
        CONSTRAINT CHK_STATE CHECK ( STATE_OF_ORDER IN ('ERROR', 'IN PROCESS', 'DELIVERED', 'SENT')),
    DATE_ORDERED DATE NOT NULL,
    TOTAL_PRICE DECIMAL(7,2) NOT NULL
        CONSTRAINT CHK_BOOK_PRICE CHECK ( TOTAL_PRICE >= 0 )
);
